---
kind: Service
apiVersion: v1
metadata:
  name: akgxyz
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    # doctl compute certificate list
    # doctl compute certificate list | awk '{ print $1 }'
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "570b919c-5c37-410f-8d0e-7f27b4e0c3cd"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "true"
spec:
  type: LoadBalancer
  selector:
    app: akgxyz
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akgxyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akgxyz
  template:
    metadata:
      labels:
        app: akgxyz
    spec:
      containers:
      - name: main
        image: bazhova/akgxyz:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

